version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=fullcycle
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "60s", "node", "./src/index.js"]
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fullcycle
    ports:
      - "3306:3306"
    restart: always
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    depends_on:
      - node-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]
