FROM node:14 as build
WORKDIR /app
ENV PATH /usr/local/bin:$PATH

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
RUN npm prune --production

FROM scratch

ENV MYSQL_HOST=db
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=password
ENV MYSQL_DATABASE=people
ENV PATH /usr/local/bin:$PATH

EXPOSE 3000
COPY --from=build /app /app
CMD ["npm", "start"]
